#ifndef CXL_CUDA_OBSERVATION_H
#define CXL_CUDA_OBSERVATION_H

#include <stdint.h>

enum cxl_cuda_observation_category_v1 {
    CXL_CUDA_OBS_SELECTED_RANGE_PLAN = 1,
    CXL_CUDA_OBS_SOURCE_LEASE = 2,
    CXL_CUDA_OBS_SOURCE_MATERIALIZATION = 3,
    CXL_CUDA_OBS_RESIDENT_LOOKUP = 4,
    CXL_CUDA_OBS_RESIDENT_TO_COMPUTE = 5,
    CXL_CUDA_OBS_GRAPH_PREPARE = 6,
    CXL_CUDA_OBS_HOST_RESULT_READ = 7,
};

#endif
